apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  iscsi:
    targetPortal: 10.10.150.2
    iqn: iqn.1992-04.com.emc:storage.Jorsat-NAS01.isci-nas
    lun: 0
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  storageClassName: openebs-iscsi
