apiVersion: v1
kind: Service
metadata:
  name: ftp-service
spec:
  type: LoadBalancer
  ports:
  - port: 21
    targetPort: 21
    protocol: TCP
    name: ftp
  - port: 30000
    targetPort: 30000
    protocol: TCP
    name: pasv-port1
  - port: 30001
    targetPort: 30001
    protocol: TCP
    name: pasv-port2
  - port: 30002
    targetPort: 30002
    protocol: TCP
    name: pasv-port3
  - port: 30003
    targetPort: 30003
    protocol: TCP
    name: pasv-port4
  - port: 30004
    targetPort: 30004
    protocol: TCP
    name: pasv-port5
  - port: 30005
    targetPort: 30005
    protocol: TCP
    name: pasv-port6
  - port: 30006
    targetPort: 30006
    protocol: TCP
    name: pasv-port7
  - port: 30007
    targetPort: 30007
    protocol: TCP
    name: pasv-port8
  - port: 30008
    targetPort: 30008
    protocol: TCP
    name: pasv-port9
  - port: 30009
    targetPort: 30009
    protocol: TCP
    name: pasv-port10
  selector:
    app: ftp

