apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: plexinc/pms-docker:latest
        ports:
        - containerPort: 32400
        volumeMounts:
        - name: plex-data
          mountPath: /config
      volumes:
      - name: plex-data
        persistentVolumeClaim:
          claimName: plex-pvc

