apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  capacity:
    storage: 100Gi # Ajusta el tamaño según tus necesidades
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany # Asegúrate de que tu NAS soporte este modo de acceso
  nfs:
    path: /nfs/minio-s3-bkps # Ruta en tu NAS que deseas montar
    server: 10.10.150.2 # Dirección IP de tu NAS

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi # Debe coincidir con el tamaño del volumen persistente
  storageClassName: "" # Dejar vacío para permitir el enlace dinámico

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: microservicios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        args:
        - server
        - /data # Esto le indica a MinIO que inicie el servidor usando el directorio /data
        ports:
        - containerPort: 9000
        env:
        - name: MINIO_ACCESS_KEY
          value: "murdok44"
        - name: MINIO_SECRET_KEY
          value: "murdok44"
        volumeMounts:
        - name: minio-data
          mountPath: /data
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-pvc

